/*
   This file was generated automatically by the Mojo IDE version B1.3.6.
   Do not edit this file directly. Instead edit the original Lucid source.
   This is a temporary file and any changes made to it will be destroyed.
*/

module shifter_13 (
    input [15:0] a,
    input [15:0] b,
    input [5:0] alufn,
    output reg [15:0] out
  );
  
  
  
  reg [3:0] shift;
  
  always @* begin
    out = 1'h0;
    shift = b[0+3-:4];
    
    case (alufn)
      6'h20: begin
        out = a << shift;
      end
      6'h21: begin
        out = a >> shift;
      end
      6'h23: begin
        out = $signed(a) >>> shift;
      end
    endcase
  end
endmodule
