/*
   This file was generated automatically by the Mojo IDE version B1.3.6.
   Do not edit this file directly. Instead edit the original Lucid source.
   This is a temporary file and any changes made to it will be destroyed.
*/

module alu_error_2 (
    input [15:0] in,
    output reg [15:0] out
  );
  
  
  
  always @* begin
    out[1+14-:15] = in[1+14-:15];
    out[0+0-:1] = ~in[0+0-:1];
  end
endmodule
